# Generated by Django 3.2.5 on 2021-07-19 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d')),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available', models.BooleanField(default=True)),
                ('size', models.CharField(max_length=200)),
                ('article', models.CharField(max_length=200)),
                ('sex', models.CharField(choices=[('M', 'Mужской'), ('Ж', 'Женский'), ('В', 'Для всех')], default='M', max_length=1)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category')),
            ],
        ),
        migrations.CreateModel(
            name='Bed_linen_sets',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
            ],
            options={
                'verbose_name': 'Комплекты постельного белья',
                'verbose_name_plural': 'Комплекты постельного белья',
            },
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Bedspreads_blankets',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
            ],
            options={
                'verbose_name': 'Покрывала, пледы',
                'verbose_name_plural': 'Покрывала, пледы',
            },
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Blankets',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
            ],
            options={
                'verbose_name': 'Одеяла',
                'verbose_name_plural': 'Одеяла',
            },
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Bristle_and_brush_products',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
                ('sub_category', models.CharField(max_length=255, verbose_name='Подкатегория')),
            ],
            options={
                'verbose_name': 'Щетинно щеточные изделия',
                'verbose_name_plural': 'Щетинно щеточные изделия',
            },
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Casual_walking_shoes',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
                ('product_type', models.CharField(max_length=255, verbose_name='Вид изделия')),
                ('mounting_method', models.CharField(max_length=255, verbose_name='Метод крепления')),
            ],
            options={
                'verbose_name': 'Обувь повседневная, прогулочная',
                'verbose_name_plural': 'Обувь повседневная, прогулочная',
            },
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Clothing_for_hunting_and_fishing',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
                ('product_type', models.CharField(max_length=255, verbose_name='Вид изделия')),
                ('season', models.CharField(max_length=255, verbose_name='Сезон')),
            ],
            options={
                'verbose_name': 'Одежда для охоты и рыбалки',
                'verbose_name_plural': 'Одежда для охоты и рыбалки',
            },
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Clothing_for_the_service_sector',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
                ('product_type', models.CharField(max_length=255, verbose_name='Вид изделия')),
                ('сomposition', models.CharField(max_length=255, verbose_name='Состав')),
            ],
            options={
                'verbose_name': 'Одежда для сферы услуг',
                'verbose_name_plural': 'Одежда для сферы услуг',
            },
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Clothing_with_limited_service_life',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
                ('sub_category', models.CharField(max_length=255, verbose_name='Подкатегория')),
                ('product_type', models.CharField(max_length=255, verbose_name='Вид изделия')),
                ('protective_properties', models.CharField(max_length=255, verbose_name='Защитные свойства')),
            ],
            options={
                'verbose_name': 'Одежда с ограниченным сроком эксплуатации',
                'verbose_name_plural': 'Одежда с ограниченным сроком эксплуатации',
            },
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Dermatological_agents',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
                ('sub_category', models.CharField(max_length=255, verbose_name='Подкатегория')),
            ],
            options={
                'verbose_name': 'Дерматологические средства',
                'verbose_name_plural': 'Дерматологические средства',
            },
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Detergents_and_household_chemicals',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
                ('sub_category', models.CharField(max_length=255, verbose_name='Подкатегория')),
            ],
            options={
                'verbose_name': 'Моющие средства и бытовая химия',
                'verbose_name_plural': 'Моющие средства и бытовая химия',
            },
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Dielectric_safety_devices',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
            ],
            options={
                'verbose_name': 'Диэлектрические средства безопасности',
                'verbose_name_plural': 'Диэлектрические средства безопасности',
            },
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Firefighting_equipment_fire_extinguishers',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
                ('sub_category', models.CharField(max_length=255, verbose_name='Подкатегория')),
            ],
            options={
                'verbose_name': 'Противопожарные средства,огнетушители',
                'verbose_name_plural': 'Противопожарные средства,огнетушители',
            },
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Gardening_tools',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
                ('sub_category', models.CharField(max_length=255, verbose_name='Подкатегория')),
            ],
            options={
                'verbose_name': 'Садово-огородный инвентарь',
                'verbose_name_plural': 'Садово-огородный инвентарь',
            },
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Hats',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
                ('product_type', models.CharField(max_length=255, verbose_name='Вид изделия')),
                ('сomposition', models.CharField(max_length=255, verbose_name='Состав')),
            ],
            options={
                'verbose_name': 'Головные уборы',
                'verbose_name_plural': 'Головные уборы',
            },
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Head_and_face_protection_products',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
                ('sub_category', models.CharField(max_length=255, verbose_name='Подкатегория')),
                ('product_type', models.CharField(max_length=255, verbose_name='Вид изделия')),
                ('mounting_method', models.CharField(max_length=255, verbose_name='Метод крепления')),
                ('features', models.CharField(max_length=255, verbose_name='Особенности')),
                ('protective_properties', models.CharField(max_length=255, verbose_name='Защитные свойства')),
            ],
            options={
                'verbose_name': 'Средства защиты головы и лица',
                'verbose_name_plural': 'Средства защиты головы и лица',
            },
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Hearing_protection_equipment',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
                ('sub_category', models.CharField(max_length=255, verbose_name='Подкатегория')),
                ('product_type', models.CharField(max_length=255, verbose_name='Вид изделия')),
                ('features', models.CharField(max_length=255, verbose_name='Особенности')),
                ('protective_properties', models.CharField(max_length=255, verbose_name='Защитные свойства')),
            ],
            options={
                'verbose_name': 'Средства защиты органов слуха',
                'verbose_name_plural': 'Средства защиты органов слуха',
            },
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Household_gloves_disposable',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
                ('appointment', models.CharField(max_length=255, verbose_name='Назначение')),
                ('protective_properties', models.CharField(max_length=255, verbose_name='Защитные свойства')),
            ],
            options={
                'verbose_name': 'Перчатки хозяйственные, одноразовые',
                'verbose_name_plural': 'Перчатки хозяйственные, одноразовые',
            },
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Household_goods',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
                ('sub_category', models.CharField(max_length=255, verbose_name='Подкатегория')),
            ],
            options={
                'verbose_name': 'Хозяйственные товары',
                'verbose_name_plural': 'Хозяйственные товары',
            },
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Insulated_mittens',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
                ('features', models.CharField(max_length=255, verbose_name='Особенности')),
                ('appointment', models.CharField(max_length=255, verbose_name='Назначение')),
                ('insulation_material', models.CharField(max_length=255, verbose_name='Утеплитель')),
                ('protective_properties', models.CharField(max_length=255, verbose_name='Защитные свойства')),
            ],
            options={
                'verbose_name': 'Рукавицы утепленные',
                'verbose_name_plural': 'Рукавицы утепленные',
            },
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Insulated_shoes',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
                ('product_type', models.CharField(max_length=255, verbose_name='Вид изделия')),
                ('appointment', models.CharField(max_length=255, verbose_name='Назначение')),
                ('mounting_method', models.CharField(max_length=255, verbose_name='Метод крепления')),
            ],
            options={
                'verbose_name': 'Обувь утепленная',
                'verbose_name_plural': 'Обувь утепленная',
            },
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Knitted_gloves',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
                ('material', models.CharField(max_length=255, verbose_name='Материал')),
                ('meets_the_requirements_of_the_FSS', models.CharField(max_length=255, verbose_name='Соответствует требованиям ФСС')),
                ('features', models.CharField(max_length=255, verbose_name='Особенности')),
                ('cuff_Type', models.CharField(max_length=255, verbose_name='Тип манжеты')),
            ],
            options={
                'verbose_name': 'Перчатки трикотажные',
                'verbose_name_plural': 'Перчатки трикотажные',
            },
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Knitwearg',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
                ('product_type', models.CharField(max_length=255, verbose_name='Вид изделия')),
            ],
            options={
                'verbose_name': 'Трикотаж',
                'verbose_name_plural': 'Трикотаж',
            },
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Kragi_vachegi',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
                ('material', models.CharField(max_length=255, verbose_name='Материал')),
                ('appointment', models.CharField(max_length=255, verbose_name='Назначение')),
                ('lining', models.CharField(max_length=255, verbose_name='Подкладка')),
                ('protective_properties', models.CharField(max_length=255, verbose_name='Защитные свойства')),
                ('product_type', models.CharField(max_length=255, verbose_name='Вид изделия')),
            ],
            options={
                'verbose_name': 'Краги, вачеги',
                'verbose_name_plural': 'Краги, вачеги',
            },
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Mattresses',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
            ],
            options={
                'verbose_name': 'Матрасы',
                'verbose_name_plural': 'Матрасы',
            },
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Means_of_protection_of_the_organs_of_vision',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
                ('sub_category', models.CharField(max_length=255, verbose_name='Подкатегория')),
                ('product_type', models.CharField(max_length=255, verbose_name='Вид изделия')),
                ('lens_coating', models.CharField(max_length=255, verbose_name='Покрытие линз')),
                ('features', models.CharField(max_length=255, verbose_name='Особенности')),
                ('protective_properties', models.CharField(max_length=255, verbose_name='Защитные свойства')),
            ],
            options={
                'verbose_name': 'Средства защиты органов зрения',
                'verbose_name_plural': 'Средства защиты органов зрения',
            },
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Medical_shoes',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
                ('product_type', models.CharField(max_length=255, verbose_name='Вид изделия')),
                ('mounting_method', models.CharField(max_length=255, verbose_name='Метод крепления')),
            ],
            options={
                'verbose_name': 'Обувь медицинская',
                'verbose_name_plural': 'Обувь медицинская',
            },
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Medical_supplies',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
                ('sub_category', models.CharField(max_length=255, verbose_name='Подкатегория')),
            ],
            options={
                'verbose_name': 'Медицинские принадлежности',
                'verbose_name_plural': 'Медицинские принадлежности',
            },
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Medical_workwear',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
                ('product_type', models.CharField(max_length=255, verbose_name='Вид изделия')),
                ('сomposition', models.CharField(max_length=255, verbose_name='Состав')),
            ],
            options={
                'verbose_name': 'Медицинская спецодежда',
                'verbose_name_plural': 'Медицинская спецодежда',
            },
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Pillows',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
            ],
            options={
                'verbose_name': 'Подушки',
                'verbose_name_plural': 'Подушки',
            },
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Protective_clothing_of_security_structures',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
                ('product_type', models.CharField(max_length=255, verbose_name='Вид изделия')),
                ('сomposition', models.CharField(max_length=255, verbose_name='Состав')),
                ('protective_properties', models.CharField(max_length=255, verbose_name='Защитные свойства')),
            ],
            options={
                'verbose_name': 'Спецодежда охранных структур',
                'verbose_name_plural': 'Спецодежда охранных структур',
            },
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Protective_equipment',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
                ('sub_category', models.CharField(max_length=255, verbose_name='Подкатегория')),
            ],
            options={
                'verbose_name': 'Оградительные средства',
                'verbose_name_plural': 'Оградительные средства',
            },
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Protective_equipment_during_highrise_works',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
                ('sub_category', models.CharField(max_length=255, verbose_name='Подкатегория')),
                ('product_type', models.CharField(max_length=255, verbose_name='Вид изделия')),
                ('meets_the_requirements_of_the_FSS', models.CharField(max_length=255, verbose_name='Соответствует требованиям ФСС')),
                ('features', models.CharField(max_length=255, verbose_name='Особенности')),
                ('protective_properties', models.CharField(max_length=255, verbose_name='Защитные свойства')),
            ],
            options={
                'verbose_name': 'Средства защиты при проведении высотных работ',
                'verbose_name_plural': 'Средства защиты при проведении высотных работ',
            },
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Protective_equipment_during_welding_operations',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
                ('sub_category', models.CharField(max_length=255, verbose_name='Подкатегория')),
                ('product_type', models.CharField(max_length=255, verbose_name='Вид изделия')),
                ('meets_the_requirements_of_the_FSS', models.CharField(max_length=255, verbose_name='Соответствует требованиям ФСС')),
                ('features', models.CharField(max_length=255, verbose_name='Особенности')),
                ('protective_properties', models.CharField(max_length=255, verbose_name='Защитные свойства')),
            ],
            options={
                'verbose_name': 'Средства защиты при проведении сварочных работ',
                'verbose_name_plural': 'Средства защиты при проведении сварочных работ',
            },
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Protective_protective_workwear',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
                ('product_type', models.CharField(max_length=255, verbose_name='Вид изделия')),
                ('сomposition', models.CharField(max_length=255, verbose_name='Состав')),
                ('protection_class', models.CharField(max_length=255, verbose_name='Класс защиты')),
                ('protective_properties', models.CharField(max_length=255, verbose_name='Защитные свойства')),
            ],
            options={
                'verbose_name': 'Спецодежда влагозащитная',
                'verbose_name_plural': 'Спецодежда влагозащитная',
            },
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='PVC_rubber_shoes',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
                ('product_type', models.CharField(max_length=255, verbose_name='Вид изделия')),
                ('appointment', models.CharField(max_length=255, verbose_name='Назначение')),
                ('features', models.CharField(max_length=255, verbose_name='Особенности')),
            ],
            options={
                'verbose_name': 'Обувь резиновая ПВХ',
                'verbose_name_plural': 'Обувь резиновая ПВХ',
            },
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Respiratory_protection_equipment',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
                ('sub_category', models.CharField(max_length=255, verbose_name='Подкатегория')),
                ('product_type', models.CharField(max_length=255, verbose_name='Вид изделия')),
                ('meets_the_requirements_of_the_FSS', models.CharField(max_length=255, verbose_name='Соответствует требованиям ФСС')),
                ('features', models.CharField(max_length=255, verbose_name='Особенности')),
                ('protective_properties', models.CharField(max_length=255, verbose_name='Защитные свойства')),
            ],
            options={
                'verbose_name': 'Средства защиты органов дыхания',
                'verbose_name_plural': 'Средства защиты органов дыхания',
            },
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Shoe_accessories',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
                ('product_type', models.CharField(max_length=255, verbose_name='Вид изделия')),
                ('insulation_material', models.CharField(max_length=255, verbose_name='Утеплитель')),
            ],
            options={
                'verbose_name': 'Аксессуары для обуви',
                'verbose_name_plural': 'Аксессуары для обуви',
            },
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Signal_workwear',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
                ('product_type', models.CharField(max_length=255, verbose_name='Вид изделия')),
                ('сomposition', models.CharField(max_length=255, verbose_name='Состав')),
                ('protection_class', models.CharField(max_length=255, verbose_name='Класс защиты')),
            ],
            options={
                'verbose_name': 'Сигнал спецодежда',
                'verbose_name_plural': 'Сигнал спецодежда',
            },
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Snow_removal_equipment',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
                ('sub_category', models.CharField(max_length=255, verbose_name='Подкатегория')),
            ],
            options={
                'verbose_name': 'Снегоуборочный инвентарь',
                'verbose_name_plural': 'Снегоуборочный инвентарь',
            },
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Special_insulated_shoes',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
                ('product_type', models.CharField(max_length=255, verbose_name='Вид изделия')),
                ('appointment', models.CharField(max_length=255, verbose_name='Назначение')),
                ('mounting_method', models.CharField(max_length=255, verbose_name='Метод крепления')),
            ],
            options={
                'verbose_name': 'Обувь специальная, утепленная',
                'verbose_name_plural': 'Обувь специальная, утепленная',
            },
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Special_workwear',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
                ('product_type', models.CharField(max_length=255, verbose_name='Вид изделия')),
                ('сomposition', models.CharField(max_length=255, verbose_name='Состав')),
                ('protective_properties', models.CharField(max_length=255, verbose_name='Защитные свойства')),
                ('protection_class', models.CharField(max_length=255, verbose_name='Класс защиты')),
            ],
            options={
                'verbose_name': 'Специальная спецодежда',
                'verbose_name_plural': 'Специальная спецодежда',
            },
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Specialized_gloves',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
                ('appointment', models.CharField(max_length=255, verbose_name='Назначение')),
                ('protection_class', models.CharField(max_length=255, verbose_name='Класс защиты')),
                ('protective_properties', models.CharField(max_length=255, verbose_name='Защитные свойства')),
                ('product_type', models.CharField(max_length=255, verbose_name='Вид изделия')),
            ],
            options={
                'verbose_name': 'Перчатки специализированные',
                'verbose_name_plural': 'Перчатки специализированные',
            },
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Split_gloves_combined',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
                ('material', models.CharField(max_length=255, verbose_name='Материал')),
                ('features', models.CharField(max_length=255, verbose_name='Особенности')),
                ('appointment', models.CharField(max_length=255, verbose_name='Назначение')),
                ('lining', models.CharField(max_length=255, verbose_name='Подкладка')),
                ('protective_properties', models.CharField(max_length=255, verbose_name='Защитные свойства')),
            ],
            options={
                'verbose_name': 'Перчатки спилковые, комбинированные',
                'verbose_name_plural': 'Перчатки спилковые, комбинированные',
            },
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Summer_shoes',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
                ('product_type', models.CharField(max_length=255, verbose_name='Вид изделия')),
                ('appointment', models.CharField(max_length=255, verbose_name='Назначение')),
            ],
            options={
                'verbose_name': 'Обувь летняя,демисезонная',
                'verbose_name_plural': 'Обувь летняя,демисезонная',
            },
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Summer_workwear',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
                ('protective_properties', models.CharField(max_length=255, verbose_name='Защитные свойства')),
                ('product_type', models.CharField(max_length=255, verbose_name='Вид изделия')),
                ('сomposition', models.CharField(max_length=255, verbose_name='Состав')),
                ('protection_class', models.CharField(max_length=255, verbose_name='Класс защиты')),
            ],
            options={
                'verbose_name': 'Летняя спецодежда',
                'verbose_name_plural': 'Летняя спецодежда',
            },
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Technical_fabrics',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
                ('sub_category', models.CharField(max_length=255, verbose_name='Подкатегория')),
            ],
            options={
                'verbose_name': 'Технические ткани',
                'verbose_name_plural': 'Технические ткани',
            },
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Terry_towels',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
            ],
            options={
                'verbose_name': 'Полотенца махровые',
                'verbose_name_plural': 'Полотенца махровые',
            },
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Waffle_towels',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
            ],
            options={
                'verbose_name': 'Полотенца вафельные',
                'verbose_name_plural': 'Полотенца вафельные',
            },
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Winter_workwear',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
                ('protective_properties', models.CharField(max_length=255, verbose_name='Защитные свойства')),
                ('product_type', models.CharField(max_length=255, verbose_name='Вид изделия')),
                ('сomposition', models.CharField(max_length=255, verbose_name='Состав')),
                ('protection_class', models.CharField(max_length=255, verbose_name='Класс защиты')),
            ],
            options={
                'verbose_name': 'Зимняя спецодежда',
                'verbose_name_plural': 'Зимняя спецодежда',
            },
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Wool_blend_gloves',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
                ('material', models.CharField(max_length=255, verbose_name='Материал')),
                ('meets_the_requirements_of_the_FSS', models.CharField(max_length=255, verbose_name='Соответствует требованиям ФСС')),
                ('features', models.CharField(max_length=255, verbose_name='Особенности')),
                ('cuff_Type', models.CharField(max_length=255, verbose_name='Тип манжеты')),
                ('appointment', models.CharField(max_length=255, verbose_name='Назначение')),
                ('insulation_material', models.CharField(max_length=255, verbose_name='Утеплитель')),
                ('сomposition', models.CharField(max_length=255, verbose_name='Состав')),
                ('protective_properties', models.CharField(max_length=255, verbose_name='Защитные свойства')),
            ],
            options={
                'verbose_name': 'Перчатки полушерстяные',
                'verbose_name_plural': 'Перчатки полушерстяные',
            },
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Working_gloves',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
                ('material', models.CharField(max_length=255, verbose_name='Материал')),
                ('appointment', models.CharField(max_length=255, verbose_name='Назначение')),
                ('lining', models.CharField(max_length=255, verbose_name='Подкладка')),
                ('protective_properties', models.CharField(max_length=255, verbose_name='Защитные свойства')),
                ('product_type', models.CharField(max_length=255, verbose_name='Вид изделия')),
                ('features', models.CharField(max_length=255, verbose_name='Особенности')),
            ],
            options={
                'verbose_name': 'Рукавицы рабочие',
                'verbose_name_plural': 'Рукавицы рабочие',
            },
            bases=('shop.product',),
        ),
    ]
