# Generated by Django 3.2.5 on 2021-07-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210725_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to='products/%Y/%m/%d', verbose_name='Фото'),
        ),
    ]
