# Generated by Django 3.2.5 on 2021-08-24 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20210726_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.TextField(max_length=200, verbose_name='Размер'),
        ),
    ]
