# Generated by Django 3.2.6 on 2021-08-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_product_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='full_name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Полное название товара'),
        ),
    ]
