# Generated by Django 3.2.6 on 2021-08-26 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_product_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Ссылка на товар(не трогать)'),
        ),
    ]
