# Generated by Django 3.2.6 on 2021-10-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_product_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AddField(
            model_name='summer_workwear',
            name='sex',
            field=models.CharField(choices=[('м', 'Mужской'), ('ж', 'Женский'), ('в', 'Для всех')], default='м', max_length=1, null=True, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='summer_workwear',
            name='size',
            field=models.TextField(max_length=500, null=True, verbose_name='Размер'),
        ),
    ]
