# Generated by Django 3.2.6 on 2021-10-14 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20211014_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summer_workwear',
            name='protection_class',
        ),
        migrations.AddField(
            model_name='bed_linen_sets',
            name='size',
            field=models.TextField(max_length=500, null=True, verbose_name='Размер'),
        ),
        migrations.AddField(
            model_name='bedspreads_blankets',
            name='size',
            field=models.TextField(max_length=500, null=True, verbose_name='Размер'),
        ),
        migrations.AddField(
            model_name='blankets',
            name='size',
            field=models.TextField(max_length=500, null=True, verbose_name='Размер'),
        ),
        migrations.AddField(
            model_name='casual_walking_shoes',
            name='sex',
            field=models.CharField(choices=[('м', 'Mужской'), ('ж', 'Женский'), ('в', 'Для всех')], default='м', max_length=1, null=True, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='casual_walking_shoes',
            name='size',
            field=models.TextField(max_length=500, null=True, verbose_name='Размер'),
        ),
        migrations.AddField(
            model_name='clothing_for_hunting_and_fishing',
            name='sex',
            field=models.CharField(choices=[('м', 'Mужской'), ('ж', 'Женский'), ('в', 'Для всех')], default='м', max_length=1, null=True, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='clothing_for_hunting_and_fishing',
            name='size',
            field=models.TextField(max_length=500, null=True, verbose_name='Размер'),
        ),
        migrations.AddField(
            model_name='clothing_for_the_service_sector',
            name='sex',
            field=models.CharField(choices=[('м', 'Mужской'), ('ж', 'Женский'), ('в', 'Для всех')], default='м', max_length=1, null=True, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='clothing_for_the_service_sector',
            name='size',
            field=models.TextField(max_length=500, null=True, verbose_name='Размер'),
        ),
        migrations.AddField(
            model_name='clothing_with_limited_service_life',
            name='size',
            field=models.TextField(max_length=500, null=True, verbose_name='Размер'),
        ),
        migrations.AddField(
            model_name='hats',
            name='sex',
            field=models.CharField(choices=[('м', 'Mужской'), ('ж', 'Женский'), ('в', 'Для всех')], default='м', max_length=1, null=True, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='hats',
            name='size',
            field=models.TextField(max_length=500, null=True, verbose_name='Размер'),
        ),
        migrations.AddField(
            model_name='head_and_face_protection_products',
            name='sex',
            field=models.CharField(choices=[('м', 'Mужской'), ('ж', 'Женский'), ('в', 'Для всех')], default='м', max_length=1, null=True, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='head_and_face_protection_products',
            name='size',
            field=models.TextField(max_length=500, null=True, verbose_name='Размер'),
        ),
        migrations.AddField(
            model_name='household_gloves_disposable',
            name='size',
            field=models.TextField(max_length=500, null=True, verbose_name='Размер'),
        ),
        migrations.AddField(
            model_name='insulated_mittens',
            name='size',
            field=models.TextField(max_length=500, null=True, verbose_name='Размер'),
        ),
        migrations.AddField(
            model_name='insulated_shoes',
            name='sex',
            field=models.CharField(choices=[('м', 'Mужской'), ('ж', 'Женский'), ('в', 'Для всех')], default='м', max_length=1, null=True, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='insulated_shoes',
            name='size',
            field=models.TextField(max_length=500, null=True, verbose_name='Размер'),
        ),
        migrations.AddField(
            model_name='knitted_gloves',
            name='sex',
            field=models.CharField(choices=[('м', 'Mужской'), ('ж', 'Женский'), ('в', 'Для всех')], default='м', max_length=1, null=True, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='knitted_gloves',
            name='size',
            field=models.TextField(max_length=500, null=True, verbose_name='Размер'),
        ),
        migrations.AddField(
            model_name='knitwearg',
            name='sex',
            field=models.CharField(choices=[('м', 'Mужской'), ('ж', 'Женский'), ('в', 'Для всех')], default='м', max_length=1, null=True, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='knitwearg',
            name='size',
            field=models.TextField(max_length=500, null=True, verbose_name='Размер'),
        ),
        migrations.AddField(
            model_name='kragi_vachegi',
            name='size',
            field=models.TextField(max_length=500, null=True, verbose_name='Размер'),
        ),
        migrations.AddField(
            model_name='mattresses',
            name='size',
            field=models.TextField(max_length=500, null=True, verbose_name='Размер'),
        ),
        migrations.AddField(
            model_name='means_of_protection_of_the_organs_of_vision',
            name='size',
            field=models.TextField(max_length=500, null=True, verbose_name='Размер'),
        ),
        migrations.AddField(
            model_name='medical_shoes',
            name='sex',
            field=models.CharField(choices=[('м', 'Mужской'), ('ж', 'Женский'), ('в', 'Для всех')], default='м', max_length=1, null=True, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='medical_shoes',
            name='size',
            field=models.TextField(max_length=500, null=True, verbose_name='Размер'),
        ),
        migrations.AddField(
            model_name='medical_workwear',
            name='sex',
            field=models.CharField(choices=[('м', 'Mужской'), ('ж', 'Женский'), ('в', 'Для всех')], default='м', max_length=1, null=True, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='medical_workwear',
            name='size',
            field=models.TextField(max_length=500, null=True, verbose_name='Размер'),
        ),
        migrations.AddField(
            model_name='pillows',
            name='size',
            field=models.TextField(max_length=500, null=True, verbose_name='Размер'),
        ),
        migrations.AddField(
            model_name='protective_clothing_of_security_structures',
            name='sex',
            field=models.CharField(choices=[('м', 'Mужской'), ('ж', 'Женский'), ('в', 'Для всех')], default='м', max_length=1, null=True, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='protective_clothing_of_security_structures',
            name='size',
            field=models.TextField(max_length=500, null=True, verbose_name='Размер'),
        ),
        migrations.AddField(
            model_name='protective_equipment_during_highrise_works',
            name='size',
            field=models.TextField(max_length=500, null=True, verbose_name='Размер'),
        ),
        migrations.AddField(
            model_name='protective_protective_workwear',
            name='sex',
            field=models.CharField(choices=[('м', 'Mужской'), ('ж', 'Женский'), ('в', 'Для всех')], default='м', max_length=1, null=True, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='protective_protective_workwear',
            name='size',
            field=models.TextField(max_length=500, null=True, verbose_name='Размер'),
        ),
        migrations.AddField(
            model_name='pvc_rubber_shoes',
            name='sex',
            field=models.CharField(choices=[('м', 'Mужской'), ('ж', 'Женский'), ('в', 'Для всех')], default='м', max_length=1, null=True, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='pvc_rubber_shoes',
            name='size',
            field=models.TextField(max_length=500, null=True, verbose_name='Размер'),
        ),
        migrations.AddField(
            model_name='shoe_accessories',
            name='size',
            field=models.TextField(max_length=500, null=True, verbose_name='Размер'),
        ),
        migrations.AddField(
            model_name='signal_workwear',
            name='sex',
            field=models.CharField(choices=[('м', 'Mужской'), ('ж', 'Женский'), ('в', 'Для всех')], default='м', max_length=1, null=True, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='signal_workwear',
            name='size',
            field=models.TextField(max_length=500, null=True, verbose_name='Размер'),
        ),
        migrations.AddField(
            model_name='snow_removal_equipment',
            name='size',
            field=models.TextField(max_length=500, null=True, verbose_name='Размер'),
        ),
        migrations.AddField(
            model_name='special_insulated_shoes',
            name='sex',
            field=models.CharField(choices=[('м', 'Mужской'), ('ж', 'Женский'), ('в', 'Для всех')], default='м', max_length=1, null=True, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='special_insulated_shoes',
            name='size',
            field=models.TextField(max_length=500, null=True, verbose_name='Размер'),
        ),
        migrations.AddField(
            model_name='special_workwear',
            name='sex',
            field=models.CharField(choices=[('м', 'Mужской'), ('ж', 'Женский'), ('в', 'Для всех')], default='м', max_length=1, null=True, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='special_workwear',
            name='size',
            field=models.TextField(max_length=500, null=True, verbose_name='Размер'),
        ),
        migrations.AddField(
            model_name='specialized_gloves',
            name='sex',
            field=models.CharField(choices=[('м', 'Mужской'), ('ж', 'Женский'), ('в', 'Для всех')], default='м', max_length=1, null=True, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='specialized_gloves',
            name='size',
            field=models.TextField(max_length=500, null=True, verbose_name='Размер'),
        ),
        migrations.AddField(
            model_name='split_gloves_combined',
            name='size',
            field=models.TextField(max_length=500, null=True, verbose_name='Размер'),
        ),
        migrations.AddField(
            model_name='summer_shoes',
            name='sex',
            field=models.CharField(choices=[('м', 'Mужской'), ('ж', 'Женский'), ('в', 'Для всех')], default='м', max_length=1, null=True, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='summer_shoes',
            name='size',
            field=models.TextField(max_length=500, null=True, verbose_name='Размер'),
        ),
        migrations.AddField(
            model_name='terry_towels',
            name='size',
            field=models.TextField(max_length=500, null=True, verbose_name='Размер'),
        ),
        migrations.AddField(
            model_name='waffle_towels',
            name='size',
            field=models.TextField(max_length=500, null=True, verbose_name='Размер'),
        ),
        migrations.AddField(
            model_name='winter_workwear',
            name='sex',
            field=models.CharField(choices=[('м', 'Mужской'), ('ж', 'Женский'), ('в', 'Для всех')], default='м', max_length=1, null=True, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='winter_workwear',
            name='size',
            field=models.TextField(max_length=500, null=True, verbose_name='Размер'),
        ),
        migrations.AddField(
            model_name='wool_blend_gloves',
            name='sex',
            field=models.CharField(choices=[('м', 'Mужской'), ('ж', 'Женский'), ('в', 'Для всех')], default='м', max_length=1, null=True, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='wool_blend_gloves',
            name='size',
            field=models.TextField(max_length=500, null=True, verbose_name='Размер'),
        ),
        migrations.AddField(
            model_name='working_gloves',
            name='size',
            field=models.TextField(max_length=500, null=True, verbose_name='Размер'),
        ),
    ]
