# Generated by Django 3.2.6 on 2021-10-27 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20211014_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bristle_and_brush_products',
            name='sub_category',
            field=models.CharField(max_length=500, verbose_name='Подкатегория'),
        ),
        migrations.AlterField(
            model_name='casual_walking_shoes',
            name='mounting_method',
            field=models.CharField(max_length=500, verbose_name='Метод крепления'),
        ),
        migrations.AlterField(
            model_name='casual_walking_shoes',
            name='product_type',
            field=models.CharField(max_length=500, verbose_name='Вид изделия'),
        ),
        migrations.AlterField(
            model_name='clothing_for_hunting_and_fishing',
            name='product_type',
            field=models.CharField(max_length=500, verbose_name='Вид изделия'),
        ),
        migrations.AlterField(
            model_name='clothing_for_hunting_and_fishing',
            name='season',
            field=models.CharField(max_length=500, verbose_name='Сезон'),
        ),
        migrations.AlterField(
            model_name='clothing_for_the_service_sector',
            name='product_type',
            field=models.CharField(max_length=500, verbose_name='Вид изделия'),
        ),
        migrations.AlterField(
            model_name='clothing_for_the_service_sector',
            name='сomposition',
            field=models.CharField(max_length=500, verbose_name='Состав'),
        ),
        migrations.AlterField(
            model_name='clothing_with_limited_service_life',
            name='product_type',
            field=models.CharField(max_length=500, verbose_name='Вид изделия'),
        ),
        migrations.AlterField(
            model_name='clothing_with_limited_service_life',
            name='protective_properties',
            field=models.CharField(max_length=500, verbose_name='Защитные свойства'),
        ),
        migrations.AlterField(
            model_name='clothing_with_limited_service_life',
            name='sub_category',
            field=models.CharField(max_length=500, verbose_name='Подкатегория'),
        ),
        migrations.AlterField(
            model_name='dermatological_agents',
            name='sub_category',
            field=models.CharField(max_length=500, verbose_name='Подкатегория'),
        ),
        migrations.AlterField(
            model_name='detergents_and_household_chemicals',
            name='sub_category',
            field=models.CharField(max_length=500, verbose_name='Подкатегория'),
        ),
        migrations.AlterField(
            model_name='firefighting_equipment_fire_extinguishers',
            name='sub_category',
            field=models.CharField(max_length=500, verbose_name='Подкатегория'),
        ),
        migrations.AlterField(
            model_name='gardening_tools',
            name='sub_category',
            field=models.CharField(max_length=500, verbose_name='Подкатегория'),
        ),
        migrations.AlterField(
            model_name='hats',
            name='product_type',
            field=models.CharField(max_length=500, verbose_name='Вид изделия'),
        ),
        migrations.AlterField(
            model_name='hats',
            name='сomposition',
            field=models.CharField(max_length=500, verbose_name='Состав'),
        ),
        migrations.AlterField(
            model_name='head_and_face_protection_products',
            name='features',
            field=models.CharField(max_length=512, verbose_name='Особенности'),
        ),
        migrations.AlterField(
            model_name='head_and_face_protection_products',
            name='mounting_method',
            field=models.CharField(max_length=500, verbose_name='Метод крепления'),
        ),
        migrations.AlterField(
            model_name='head_and_face_protection_products',
            name='product_type',
            field=models.CharField(max_length=500, verbose_name='Вид изделия'),
        ),
        migrations.AlterField(
            model_name='head_and_face_protection_products',
            name='protective_properties',
            field=models.CharField(max_length=500, verbose_name='Защитные свойства'),
        ),
        migrations.AlterField(
            model_name='head_and_face_protection_products',
            name='sub_category',
            field=models.CharField(max_length=500, verbose_name='Подкатегория'),
        ),
        migrations.AlterField(
            model_name='hearing_protection_equipment',
            name='features',
            field=models.CharField(max_length=512, verbose_name='Особенности'),
        ),
        migrations.AlterField(
            model_name='hearing_protection_equipment',
            name='product_type',
            field=models.CharField(max_length=500, verbose_name='Вид изделия'),
        ),
        migrations.AlterField(
            model_name='hearing_protection_equipment',
            name='protective_properties',
            field=models.CharField(max_length=500, verbose_name='Защитные свойства'),
        ),
        migrations.AlterField(
            model_name='hearing_protection_equipment',
            name='sub_category',
            field=models.CharField(max_length=500, verbose_name='Подкатегория'),
        ),
        migrations.AlterField(
            model_name='household_gloves_disposable',
            name='appointment',
            field=models.CharField(max_length=500, verbose_name='Назначение'),
        ),
        migrations.AlterField(
            model_name='household_gloves_disposable',
            name='protective_properties',
            field=models.CharField(max_length=500, verbose_name='Защитные свойства'),
        ),
        migrations.AlterField(
            model_name='household_goods',
            name='sub_category',
            field=models.CharField(max_length=500, verbose_name='Подкатегория'),
        ),
        migrations.AlterField(
            model_name='insulated_mittens',
            name='appointment',
            field=models.CharField(max_length=500, verbose_name='Назначение'),
        ),
        migrations.AlterField(
            model_name='insulated_mittens',
            name='features',
            field=models.CharField(max_length=512, verbose_name='Особенности'),
        ),
        migrations.AlterField(
            model_name='insulated_mittens',
            name='insulation_material',
            field=models.CharField(max_length=500, verbose_name='Утеплитель'),
        ),
        migrations.AlterField(
            model_name='insulated_mittens',
            name='protective_properties',
            field=models.CharField(max_length=500, verbose_name='Защитные свойства'),
        ),
        migrations.AlterField(
            model_name='insulated_shoes',
            name='appointment',
            field=models.CharField(max_length=500, verbose_name='Назначение'),
        ),
        migrations.AlterField(
            model_name='insulated_shoes',
            name='mounting_method',
            field=models.CharField(max_length=500, verbose_name='Метод крепления'),
        ),
        migrations.AlterField(
            model_name='insulated_shoes',
            name='product_type',
            field=models.CharField(max_length=500, verbose_name='Вид изделия'),
        ),
        migrations.AlterField(
            model_name='knitted_gloves',
            name='cuff_Type',
            field=models.CharField(max_length=500, verbose_name='Тип манжеты'),
        ),
        migrations.AlterField(
            model_name='knitted_gloves',
            name='features',
            field=models.CharField(max_length=512, verbose_name='Особенности'),
        ),
        migrations.AlterField(
            model_name='knitted_gloves',
            name='material',
            field=models.CharField(max_length=500, verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='knitted_gloves',
            name='meets_the_requirements_of_the_FSS',
            field=models.CharField(max_length=500, verbose_name='Соответствует требованиям ФСС'),
        ),
        migrations.AlterField(
            model_name='knitwearg',
            name='product_type',
            field=models.CharField(max_length=500, verbose_name='Вид изделия'),
        ),
        migrations.AlterField(
            model_name='kragi_vachegi',
            name='appointment',
            field=models.CharField(max_length=500, verbose_name='Назначение'),
        ),
        migrations.AlterField(
            model_name='kragi_vachegi',
            name='lining',
            field=models.CharField(max_length=500, verbose_name='Подкладка'),
        ),
        migrations.AlterField(
            model_name='kragi_vachegi',
            name='material',
            field=models.CharField(max_length=500, verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='kragi_vachegi',
            name='product_type',
            field=models.CharField(max_length=500, verbose_name='Вид изделия'),
        ),
        migrations.AlterField(
            model_name='kragi_vachegi',
            name='protective_properties',
            field=models.CharField(max_length=500, verbose_name='Защитные свойства'),
        ),
        migrations.AlterField(
            model_name='means_of_protection_of_the_organs_of_vision',
            name='features',
            field=models.CharField(max_length=512, verbose_name='Особенности'),
        ),
        migrations.AlterField(
            model_name='means_of_protection_of_the_organs_of_vision',
            name='lens_coating',
            field=models.CharField(max_length=500, verbose_name='Покрытие линз'),
        ),
        migrations.AlterField(
            model_name='means_of_protection_of_the_organs_of_vision',
            name='product_type',
            field=models.CharField(max_length=500, verbose_name='Вид изделия'),
        ),
        migrations.AlterField(
            model_name='means_of_protection_of_the_organs_of_vision',
            name='protective_properties',
            field=models.CharField(max_length=500, verbose_name='Защитные свойства'),
        ),
        migrations.AlterField(
            model_name='means_of_protection_of_the_organs_of_vision',
            name='sub_category',
            field=models.CharField(max_length=500, verbose_name='Подкатегория'),
        ),
        migrations.AlterField(
            model_name='medical_shoes',
            name='mounting_method',
            field=models.CharField(max_length=500, verbose_name='Метод крепления'),
        ),
        migrations.AlterField(
            model_name='medical_shoes',
            name='product_type',
            field=models.CharField(max_length=500, verbose_name='Вид изделия'),
        ),
        migrations.AlterField(
            model_name='medical_supplies',
            name='sub_category',
            field=models.CharField(max_length=500, verbose_name='Подкатегория'),
        ),
        migrations.AlterField(
            model_name='medical_workwear',
            name='product_type',
            field=models.CharField(max_length=500, verbose_name='Вид изделия'),
        ),
        migrations.AlterField(
            model_name='medical_workwear',
            name='сomposition',
            field=models.CharField(max_length=500, verbose_name='Состав'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='protective_clothing_of_security_structures',
            name='product_type',
            field=models.CharField(max_length=500, verbose_name='Вид изделия'),
        ),
        migrations.AlterField(
            model_name='protective_clothing_of_security_structures',
            name='protective_properties',
            field=models.CharField(max_length=500, verbose_name='Защитные свойства'),
        ),
        migrations.AlterField(
            model_name='protective_clothing_of_security_structures',
            name='сomposition',
            field=models.CharField(max_length=500, verbose_name='Состав'),
        ),
        migrations.AlterField(
            model_name='protective_equipment',
            name='sub_category',
            field=models.CharField(max_length=500, verbose_name='Подкатегория'),
        ),
        migrations.AlterField(
            model_name='protective_equipment_during_highrise_works',
            name='features',
            field=models.CharField(max_length=512, verbose_name='Особенности'),
        ),
        migrations.AlterField(
            model_name='protective_equipment_during_highrise_works',
            name='meets_the_requirements_of_the_FSS',
            field=models.CharField(max_length=500, verbose_name='Соответствует требованиям ФСС'),
        ),
        migrations.AlterField(
            model_name='protective_equipment_during_highrise_works',
            name='product_type',
            field=models.CharField(max_length=500, verbose_name='Вид изделия'),
        ),
        migrations.AlterField(
            model_name='protective_equipment_during_highrise_works',
            name='protective_properties',
            field=models.CharField(max_length=500, verbose_name='Защитные свойства'),
        ),
        migrations.AlterField(
            model_name='protective_equipment_during_highrise_works',
            name='sub_category',
            field=models.CharField(max_length=500, verbose_name='Подкатегория'),
        ),
        migrations.AlterField(
            model_name='protective_equipment_during_welding_operations',
            name='features',
            field=models.CharField(max_length=512, verbose_name='Особенности'),
        ),
        migrations.AlterField(
            model_name='protective_equipment_during_welding_operations',
            name='meets_the_requirements_of_the_FSS',
            field=models.CharField(max_length=500, verbose_name='Соответствует требованиям ФСС'),
        ),
        migrations.AlterField(
            model_name='protective_equipment_during_welding_operations',
            name='product_type',
            field=models.CharField(max_length=500, verbose_name='Вид изделия'),
        ),
        migrations.AlterField(
            model_name='protective_equipment_during_welding_operations',
            name='protective_properties',
            field=models.CharField(max_length=500, verbose_name='Защитные свойства'),
        ),
        migrations.AlterField(
            model_name='protective_equipment_during_welding_operations',
            name='sub_category',
            field=models.CharField(max_length=500, verbose_name='Подкатегория'),
        ),
        migrations.AlterField(
            model_name='protective_protective_workwear',
            name='product_type',
            field=models.CharField(max_length=500, verbose_name='Вид изделия'),
        ),
        migrations.AlterField(
            model_name='protective_protective_workwear',
            name='protection_class',
            field=models.CharField(max_length=500, verbose_name='Класс защиты'),
        ),
        migrations.AlterField(
            model_name='protective_protective_workwear',
            name='protective_properties',
            field=models.CharField(max_length=500, verbose_name='Защитные свойства'),
        ),
        migrations.AlterField(
            model_name='protective_protective_workwear',
            name='сomposition',
            field=models.CharField(max_length=500, verbose_name='Состав'),
        ),
        migrations.AlterField(
            model_name='pvc_rubber_shoes',
            name='appointment',
            field=models.CharField(max_length=500, verbose_name='Назначение'),
        ),
        migrations.AlterField(
            model_name='pvc_rubber_shoes',
            name='features',
            field=models.CharField(max_length=512, verbose_name='Особенности'),
        ),
        migrations.AlterField(
            model_name='pvc_rubber_shoes',
            name='product_type',
            field=models.CharField(max_length=500, verbose_name='Вид изделия'),
        ),
        migrations.AlterField(
            model_name='respiratory_protection_equipment',
            name='features',
            field=models.CharField(max_length=512, verbose_name='Особенности'),
        ),
        migrations.AlterField(
            model_name='respiratory_protection_equipment',
            name='meets_the_requirements_of_the_FSS',
            field=models.CharField(max_length=500, verbose_name='Соответствует требованиям ФСС'),
        ),
        migrations.AlterField(
            model_name='respiratory_protection_equipment',
            name='product_type',
            field=models.CharField(max_length=500, verbose_name='Вид изделия'),
        ),
        migrations.AlterField(
            model_name='respiratory_protection_equipment',
            name='protective_properties',
            field=models.CharField(max_length=500, verbose_name='Защитные свойства'),
        ),
        migrations.AlterField(
            model_name='respiratory_protection_equipment',
            name='sub_category',
            field=models.CharField(max_length=500, verbose_name='Подкатегория'),
        ),
        migrations.AlterField(
            model_name='shoe_accessories',
            name='insulation_material',
            field=models.CharField(max_length=500, verbose_name='Утеплитель'),
        ),
        migrations.AlterField(
            model_name='shoe_accessories',
            name='product_type',
            field=models.CharField(max_length=500, verbose_name='Вид изделия'),
        ),
        migrations.AlterField(
            model_name='signal_workwear',
            name='product_type',
            field=models.CharField(max_length=500, verbose_name='Вид изделия'),
        ),
        migrations.AlterField(
            model_name='signal_workwear',
            name='protection_class',
            field=models.CharField(max_length=500, verbose_name='Класс защиты'),
        ),
        migrations.AlterField(
            model_name='signal_workwear',
            name='сomposition',
            field=models.CharField(max_length=500, verbose_name='Состав'),
        ),
        migrations.AlterField(
            model_name='snow_removal_equipment',
            name='sub_category',
            field=models.CharField(max_length=500, verbose_name='Подкатегория'),
        ),
        migrations.AlterField(
            model_name='special_insulated_shoes',
            name='appointment',
            field=models.CharField(max_length=500, verbose_name='Назначение'),
        ),
        migrations.AlterField(
            model_name='special_insulated_shoes',
            name='mounting_method',
            field=models.CharField(max_length=500, verbose_name='Метод крепления'),
        ),
        migrations.AlterField(
            model_name='special_insulated_shoes',
            name='product_type',
            field=models.CharField(max_length=500, verbose_name='Вид изделия'),
        ),
        migrations.AlterField(
            model_name='special_workwear',
            name='product_type',
            field=models.CharField(max_length=500, verbose_name='Вид изделия'),
        ),
        migrations.AlterField(
            model_name='special_workwear',
            name='protection_class',
            field=models.CharField(max_length=500, verbose_name='Класс защиты'),
        ),
        migrations.AlterField(
            model_name='special_workwear',
            name='protective_properties',
            field=models.TextField(max_length=500, verbose_name='Защитные свойства'),
        ),
        migrations.AlterField(
            model_name='special_workwear',
            name='сomposition',
            field=models.CharField(max_length=500, verbose_name='Состав'),
        ),
        migrations.AlterField(
            model_name='specialized_gloves',
            name='appointment',
            field=models.CharField(max_length=500, verbose_name='Назначение'),
        ),
        migrations.AlterField(
            model_name='specialized_gloves',
            name='product_type',
            field=models.CharField(max_length=500, verbose_name='Вид изделия'),
        ),
        migrations.AlterField(
            model_name='specialized_gloves',
            name='protection_class',
            field=models.CharField(max_length=500, verbose_name='Класс защиты'),
        ),
        migrations.AlterField(
            model_name='specialized_gloves',
            name='protective_properties',
            field=models.CharField(max_length=500, verbose_name='Защитные свойства'),
        ),
        migrations.AlterField(
            model_name='split_gloves_combined',
            name='appointment',
            field=models.CharField(max_length=500, verbose_name='Назначение'),
        ),
        migrations.AlterField(
            model_name='split_gloves_combined',
            name='features',
            field=models.CharField(max_length=512, verbose_name='Особенности'),
        ),
        migrations.AlterField(
            model_name='split_gloves_combined',
            name='lining',
            field=models.CharField(max_length=500, verbose_name='Подкладка'),
        ),
        migrations.AlterField(
            model_name='split_gloves_combined',
            name='material',
            field=models.CharField(max_length=500, verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='split_gloves_combined',
            name='protective_properties',
            field=models.CharField(max_length=500, verbose_name='Защитные свойства'),
        ),
        migrations.AlterField(
            model_name='summer_shoes',
            name='appointment',
            field=models.CharField(max_length=500, verbose_name='Назначение'),
        ),
        migrations.AlterField(
            model_name='summer_shoes',
            name='product_type',
            field=models.CharField(max_length=500, verbose_name='Вид изделия'),
        ),
        migrations.AlterField(
            model_name='summer_workwear',
            name='product_type',
            field=models.CharField(max_length=500, verbose_name='Вид изделия'),
        ),
        migrations.AlterField(
            model_name='summer_workwear',
            name='protective_properties',
            field=models.CharField(max_length=500, verbose_name='Защитные свойства'),
        ),
        migrations.AlterField(
            model_name='summer_workwear',
            name='сomposition',
            field=models.CharField(max_length=500, verbose_name='Состав'),
        ),
        migrations.AlterField(
            model_name='technical_fabrics',
            name='sub_category',
            field=models.CharField(max_length=500, verbose_name='Подкатегория'),
        ),
        migrations.AlterField(
            model_name='winter_workwear',
            name='product_type',
            field=models.CharField(max_length=500, verbose_name='Вид изделия'),
        ),
        migrations.AlterField(
            model_name='winter_workwear',
            name='protection_class',
            field=models.CharField(max_length=500, verbose_name='Класс защиты'),
        ),
        migrations.AlterField(
            model_name='winter_workwear',
            name='protective_properties',
            field=models.CharField(max_length=500, verbose_name='Защитные свойства'),
        ),
        migrations.AlterField(
            model_name='winter_workwear',
            name='сomposition',
            field=models.CharField(max_length=500, verbose_name='Состав'),
        ),
        migrations.AlterField(
            model_name='wool_blend_gloves',
            name='appointment',
            field=models.CharField(max_length=500, verbose_name='Назначение'),
        ),
        migrations.AlterField(
            model_name='wool_blend_gloves',
            name='cuff_Type',
            field=models.CharField(max_length=500, verbose_name='Тип манжеты'),
        ),
        migrations.AlterField(
            model_name='wool_blend_gloves',
            name='features',
            field=models.CharField(max_length=512, verbose_name='Особенности'),
        ),
        migrations.AlterField(
            model_name='wool_blend_gloves',
            name='insulation_material',
            field=models.CharField(max_length=500, verbose_name='Утеплитель'),
        ),
        migrations.AlterField(
            model_name='wool_blend_gloves',
            name='material',
            field=models.CharField(max_length=500, verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='wool_blend_gloves',
            name='meets_the_requirements_of_the_FSS',
            field=models.CharField(max_length=500, verbose_name='Соответствует требованиям ФСС'),
        ),
        migrations.AlterField(
            model_name='wool_blend_gloves',
            name='protective_properties',
            field=models.CharField(max_length=500, verbose_name='Защитные свойства'),
        ),
        migrations.AlterField(
            model_name='wool_blend_gloves',
            name='сomposition',
            field=models.CharField(max_length=500, verbose_name='Состав'),
        ),
        migrations.AlterField(
            model_name='working_gloves',
            name='appointment',
            field=models.CharField(max_length=500, verbose_name='Назначение'),
        ),
        migrations.AlterField(
            model_name='working_gloves',
            name='features',
            field=models.CharField(max_length=512, verbose_name='Особенности'),
        ),
        migrations.AlterField(
            model_name='working_gloves',
            name='lining',
            field=models.CharField(max_length=500, verbose_name='Подкладка'),
        ),
        migrations.AlterField(
            model_name='working_gloves',
            name='material',
            field=models.CharField(max_length=500, verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='working_gloves',
            name='product_type',
            field=models.CharField(max_length=500, verbose_name='Вид изделия'),
        ),
        migrations.AlterField(
            model_name='working_gloves',
            name='protective_properties',
            field=models.CharField(max_length=500, verbose_name='Защитные свойства'),
        ),
    ]
