# Generated by Django 3.2.6 on 2021-10-27 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products_Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, upload_to='products/', verbose_name='Картинки товара')),
            ],
            options={
                'verbose_name': 'Файл с фото',
                'verbose_name_plural': 'Файл с фото',
            },
        ),
    ]
