# Generated by Django 3.2.6 on 2021-10-27 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_photo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products_photo',
            name='image',
            field=models.FileField(blank=True, upload_to='', verbose_name='Картинки товара'),
        ),
    ]
