# Generated by Django 3.2.5 on 2021-08-12 13:31

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('slug', models.SlugField(max_length=250, unique_for_date='publish')),
                ('img', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Превью изображение')),
                ('body', models.TextField(verbose_name='Текст статьи')),
            ],
            managers=[
                ('bject', django.db.models.manager.Manager()),
            ],
        ),
    ]
