# Generated by Django 3.2.5 on 2021-08-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210814_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='main_img',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Главное изображение'),
        ),
    ]
